### ISSUE TITLE
North-Gyeongsang, South-Gyeongsang edit plz(?)

### ISSUE THREAD

**Issue by ghost** [wonderlandpark/Administrative-divisions-of-South-Korea#1]
고속도로(?)를 가다보면
경상북도, 경상남도에 

> 발음이 나는대로

적혀있습니다.
외국인들이 보면 `오해`의 소지가 있을 수 있어서
수정을 요청합니다.
[Gyeongsnagbuk-do link](https://www.google.com/search?q=gyeongsangbuk-do) 
[Gyeongsnagnam-do link](https://www.google.com/search?q=gyeongsangnam-do)

**Comment by wonderlandpark** [comment]
늦게 확인하여 죄송합니다!

**Comment by wonderlandpark** [comment]
`Gyeongsang` 의 표기는 위키피디아 기준입니다!
